# arxivの学問領域の指定
subject: 'cat:hep-th.* OR cat:gr-qc.* OR cat:cond-mat.dis-nn OR cat:cond-mat.stat-mech OR cat:cond-mat.str-el'

# 検索キーワード
keywords:
        entanglement entropy: 5
        entanglement: 4
        holography: 5
        holographic: 5
        quantum information: 2
        tensor network: 3
        information geometry: 3
        quantum circuit: 2
        weak value: 1
        weak measurement: 1
        AdS/CFT: 4
        entropy: 3
        Berry: 1
        modular: 1

# 通知の閾値
score_threshold: 0
